require('plugins.lualine')
require('plugins.treesitter')
require('plugins.nvim-tree')
require('plugins.blink')
require('plugins.kanagawa')
require('plugins.oil')
require('plugins.flash')
require('plugins.snacks')
